Repository simelo/rextporter, pull requests merged in 2018-11, with the labels that each got.

#10 [ci] refs #1 - Github PR template
  .github/pull_request_template.md
Labels: stdev, wip

#16 closes #13 Load service inventory from file
  CHANGELOG.md
  Makefile
  cmd/rextporter/main.go
  conf/default/skycoin/metrics.toml
  conf/default/skycoin/service.toml
  src/config/config.go
  src/config/service.go
  src/config/serviceconfigfromfile.go
  src/config/serviceconfigreader.go
  src/exporter/collector.go
  src/exporter/exporter.go
  test/integration/integration_test.go
  test/integration/metrics.toml
  test/integration/service.toml
  test/integration/simple.toml
Labels: feature, stdev, wip

#17 fixes #14 - global service configuration
  .gitignore
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  cmd/rextporter/main.go
  conf/default/skycoin/metrics.toml
  conf/default/skycoin/service.toml
  src/client/metric_client.go
  src/client/token_client.go
  src/config/config.go
  src/config/config_render.go
  src/config/serviceconfigfromfile.go
  src/exporter/collector.go
  src/exporter/exporter.go
  src/exporter/metric.go
  src/util/error.go
  src/util/file/fs.go
  test/integration/fake_skycoin_node.go
  test/integration/integration_test.go
  test/integration/metrics.toml
  test/integration/service.toml
  test/integration/testrand/rand.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/shibukawa/configdir/LICENSE
  vendor/github.com/shibukawa/configdir/README.rst
  vendor/github.com/shibukawa/configdir/config.go
  vendor/github.com/shibukawa/configdir/config_darwin.go
  vendor/github.com/shibukawa/configdir/config_windows.go
  vendor/github.com/shibukawa/configdir/config_xdg.go
  vendor/golang.org/x/sys/unix/asm_linux_ppc64x.s
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_unix_gc.go
  vendor/golang.org/x/sys/unix/syscall_unix_gc_ppc64x.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zsyscall_dragonfly_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
Labels: stdev, wip

#20 closes #19 map configuration to work across multiple services
  CHANGELOG.md
  TODO
  src/client/metric_client.go
  src/client/metric_client_test.go
  src/config/config.go
  src/config/config_render.go
  src/config/metric.go
  src/config/metric_test.go
  src/config/service.go
  src/config/serviceconfigfromfile.go
  src/exporter/metric.go
  src/util/file/fs.go
  test/integration/integration_test.go
  test/integration/testrand/rand.go
Labels: feature, stdev, wip

#26 Denisacostaq t23 autodetect content type when use a service in proxy mode
  Gopkg.lock
  Gopkg.toml
  src/client/metric_client.go
  src/client/proxy_metric_client.go
  src/client/token_client.go
  src/config/config.go
  src/config/config_render.go
  src/config/service.go
  src/exporter/exporter.go
  test/integration/integration_test.go
  vendor/github.com/NYTimes/gziphandler/.gitignore
  vendor/github.com/NYTimes/gziphandler/.travis.yml
  vendor/github.com/NYTimes/gziphandler/CODE_OF_CONDUCT.md
  vendor/github.com/NYTimes/gziphandler/CONTRIBUTING.md
  vendor/github.com/NYTimes/gziphandler/LICENSE
  vendor/github.com/NYTimes/gziphandler/README.md
  vendor/github.com/NYTimes/gziphandler/gzip.go
  vendor/github.com/NYTimes/gziphandler/gzip_go18.go
Labels: feature, stdev, wip

#28 Denisacostaq t27 metrics as proxy fix bugs
  Makefile
  src/client/metric_client.go
  src/client/proxy_metric_client.go
  src/client/token_client.go
  src/config/config.go
  src/exporter/exporter.go
  test/integration/integration_test.go
  test/integration/testrand/rand.go
Labels: bug, stdev, wip

#35 Denisacostaq t29 add support for histrogram metrics
  src/client/metric_client.go
  src/config/config_render.go
  src/config/metric.go
  src/exporter/collector.go
  src/exporter/metric.go
Labels: stdev, wip

#36 Denisacostaq t34 avoid panic from must operations
  CHANGELOG.md
  src/exporter/collector.go
Labels: bug, stdev, wip

#39 Denisacostaq t37 be able to define vector metrics(counter and gauge) mapping some label.
  CHANGELOG.md
  README.md
  TODO
  src/client/base_client.go
  src/client/client.go
  src/client/histogram.go
  src/client/metric_client.go
  src/client/numeric.go
  src/client/numeric_test.go
  src/client/numeric_vec.go
  src/client/proxy.go
  src/client/token.go
  src/config/config.go
  src/config/config_render.go
  src/config/metric.go
  src/config/service.go
  src/exporter/collector.go
  src/exporter/metric.go
Labels: feature, stdev, wip

#47 Denisacostaq t30 a service can have some custom metrics and act as a metrics proxy
  CHANGELOG.md
  README.md
  src/client/client.go
  src/client/numeric_test.go
  src/client/proxy.go
  src/config/config.go
  src/config/config_render.go
  src/config/metric_test.go
  src/config/service.go
  src/config/service_test.go
  src/config/serviceconfigfromfile.go
  src/util/str.go
  test/integration/integration_test.go
Labels: feature, stdev, wip

#48 Denisacostaq t45 remove coupling to global config instance
  cmd/rextporter/main.go
  src/client/numeric_test.go
  src/config/config.go
  src/config/metric_test.go
  src/exporter/collector.go
  src/exporter/exporter.go
  src/exporter/metric.go
  test/integration/integration_test.go
Labels: enhancement, stdev, wip
