Repository simelo/rextporter, pull requests merged in 2018-12, with the labels that each got.

#55 refs #53 - reuse policies of http.request instances
  src/client/api_rest.go
  src/client/client.go
  src/client/client_catcher.go
  src/client/metrics_forwader.go
  src/client/token.go
  src/exporter/collector.go
  src/exporter/exporter.go
  src/exporter/metric.go
  src/scrapper/histogram.go
  src/scrapper/init.go
  src/scrapper/metrics_forwader.go
  src/scrapper/numeric.go
  src/scrapper/numeric_test.go
  src/scrapper/numeric_vec.go
  src/scrapper/scrapper.go
  src/scrapper/worker_queue.go
Labels: enhancement, stdev, wip

#59 fixes #8 - Travis CI build badge
  README.md
Labels: stdev, wip

#65 [ci] fixes #64 - Github issue and PR templates
  .github/issue_template.md
  .github/pull_request_template.md
Labels: stdev, wip

#62 fixes #54 fixes #61 automatically generated labels and time series
  CHANGELOG.md
  src/cache/cache.go
  src/cache/cache_test.go
  src/cache/memory.go
  src/client/api_rest.go
  src/client/client.go
  src/client/client_catcher.go
  src/client/metrics_forwader.go
  src/client/token.go
  src/config/service.go
  src/exporter/collector.go
  src/exporter/default_metrics.go
  src/exporter/exporter.go
  src/exporter/metric.go
  src/scrapper/histogram.go
  src/scrapper/metrics_forwader.go
  src/scrapper/numeric.go
  src/scrapper/numeric_test.go
  src/scrapper/numeric_vec.go
  src/scrapper/scrapper.go
  src/scrapper/worker_queue.go
  src/util/metrics/default_fordwader_metrics.go
  test/integration/integration_test.go
Labels: feature, stdev, wip
